# Generated by Django 3.2.5 on 2022-07-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_pw', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('user_birth', models.DateField()),
                ('user_gender', models.SmallIntegerField(null=True)),
                ('date_joined', models.DateTimeField()),
            ],
        ),
    ]
