# Generated by Django 3.2.5 on 2022-07-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
